apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvclocalconor
  labels:
    
    helm.sh/chart: test-obj-store-0.1.0
    app.kubernetes.io/name: test-obj-store
    app.kubernetes.io/instance: test-obj-store
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: conor-sc-local
  volumeName: conor-pv-local



